<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WarpCLR.Backend.AMDGPU\WarpCLR.Backend.AMDGPU.csproj" />
    <ProjectReference Include="..\WarpCLR.Backend.CoreCLR\WarpCLR.Backend.CoreCLR.csproj" />
    <ProjectReference Include="..\WarpCLR.Backend.SPIRV\WarpCLR.Backend.SPIRV.csproj" />
    <ProjectReference Include="..\WarpCLR.Backend.NVPTX\WarpCLR.Backend.NVPTX.csproj" />
    <ProjectReference Include="..\WarpCLR.Compiler\WarpCLR.Compiler.csproj" />
    <ProjectReference Include="..\WarpCLR.IR\WarpCLR.IR.csproj" />
    <ProjectReference Include="..\WarpCLR.Runtime.Host\WarpCLR.Runtime.Host.csproj" />
    <ProjectReference Include="..\WarpCLR.Sdk\WarpCLR.Sdk.csproj" />
    <ProjectReference Include="..\WarpCLR.Verifier\WarpCLR.Verifier.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
